// Cs/En strings for the homepage language toggle, moved verbatim from the former inline script.
export const LANG = {
  cs:{
    "sc1-more":"Zjistit více →","sc7-more":"Zjistit více →",
    "nl-svc":"Služby","nl-promo":"Akce","nl-vouch":"Dárkové poukazy","nl-contact":"Kontakt","nav-book":"Rezervace",
    "h-eyebrow":"Wellness centrum · Praha 6 – Břevnov","h-title":"Místo, kde <em>tělo<br>& mysl</em> odpočinou",
    "h-sub":"Thajské masáže, kosmetika, permanentní makeup a péče o nehty — vše pod jednou střechou s 17 lety zkušeností.",
    "h-cta1":"Rezervovat termín","h-cta2":"Naše služby","h-scroll":"Scroll",
    "s1":"let zkušeností","s2":"druhů služeb","s3":"specialistů","s4":"sleva při otevření",
    "svc-ey":"Naše služby","svc-ttl":"Péče, která <em>opravdu funguje</em>",
    "svc-sub":"Od relaxačních masáží po kosmetické zákroky — tým odborníků se postará o každý detail.",
    "sc1-n":"Masáže","sc1-d":"Tradiční thajské masáže, olejové, horké kameny, bylinná a aromatická masáž. Uvolněte napětí a obnovte rovnováhu těla.","sc1-p":"od 490 Kč",
    "sc2-n":"Párová masáž","sc2-d":"Relaxace pro dva — sdílený zážitek plný pohody a klidu. Ideální dárek pro páry i přátele.","sc2-p":"od 1 490 Kč",
    "sc3-n":"Kosmetika","sc3-d":"Hloubkové ošetření pleti, léčba akné, anti-aging procedury, depilace a líčení pro každou příležitost.","sc3-p":"od 180 Kč",
    "sc4-n":"Permanentní makeup","sc4-d":"Mikroblading obočí, PMU rty a obočí. Přirozený výsledek, který vydrží.","sc4-p":"od 3 500 Kč",
    "sc5-n":"Obočí & řasy","sc5-d":"Laminace, prodlužování řas, lash lifting, barvení a úprava tvaru. Dokonalý pohled každý den.","sc5-p":"od 150 Kč",
    "sc6-n":"Nehty","sc6-d":"Manikúra, pedikúra, Shellac/Gellac, Footlogix a gelové nehty. Péče o vaše ruce a nohy od špiček.","sc6-p":"od 250 Kč",
    "sc7-n":"Kadeřnictví","sc7-d":"Střihy, barvení, baleáž a vlasové kúry pro muže, ženy i děti. Profesionální péče o vaše vlasy.","sc7-p":"od 100 Kč",
    "svc-book":"Rezervovat službu",
    "sf-ey":"O nás","sf-ttl":"17 let zkušeností<br><em>v péči o Vás</em>",
    "sf-sub":"GoldenZen vznikl s jedinou vizí — nabídnout v Praze 6 místo, kde se cítíte skutečně dobře.",
    "sf-cta":"Rezervovat nyní",
    "pr-ey":"Aktuální akce","pr-ttl":"Výhodné <em>nabídky</em>","pr-sub":"Využijte naše aktuální akce a dopřejte si více za méně.",
    "pb1":"Otevření","pt1":"30 % sleva","pd1":"Při otevření salonu získáte 30% slevu na veškeré služby a produkty.","ph1":"Platí na všechny služby",
    "pb2":"Věrnostní program","pt2":"10× a 1 zdarma","pd2":"Přijďte desetkrát a jedenáctá návštěva je na nás.","ph2":"Masáže & kosmetika",
    "pb3":"Měsíční nabídka","pt3":"30 % na delší procedury","pd3":"Tento měsíc 30% sleva na procedury nad 60 minut.","ph3":"Procedury nad 60 minut",
    "vo-ey":"Dárkové poukazy","vo-ttl":"Darujte <em>zážitek</em>,<br>ne věc",
    "vo-sub":"Dárkový poukaz GoldenZen je ideální dárek — narozeniny, výročí nebo jen proto, že na někoho myslíte.",
    "vo-cta":"Objednat poukaz","vc-lbl":"GoldenZen · Dárkový poukaz","vc-val":"Wellness centrum Praha 6",
    "vc-b1":"Bonus 30 %","vc-b2":"při nákupu nad 5 000 Kč","vc-b3":"Bonus 40 %","vc-b4":"při nákupu nad 15 000 Kč",
    "ct-ey":"Kontakt","ct-ttl":"Navštivte <em>nás</em>","ci-addr-l":"Adresa","ci-ph-l":"Telefon","ci-hrs-l":"Otevírací doba",
    "ci-hrs-v":"Po – Pá: 9:00 – 21:00<br>So – Ne: 10:00 – 21:00",
    "ci-ig-l":"Instagram","ci-fb-l":"Facebook",
    "bk-ey":"Online rezervace","bk-ttl":"Rezervujte si <em>svůj čas</em><br>ještě dnes",
    "bk-sub":"Vyberte službu, zvolte termín a my se postaráme o zbytek. Rychle, jednoduše, online.",
    "bk-cta":"Přejít na rezervaci","ft-copy":"© 2026 GoldenZen · Bělohorská 1686/118, Praha 6 – Břevnov","ft-legal":"Ochrana osobních údajů","ft-s1":"Kadeřnictví","ft-s2":"Pánské kadeřnictví","ft-s3":"Dámské kadeřnictví","ft-s4":"Barvení vlasů","ft-s5":"Masáže","ft-s6":"Thajské masáže"
  },
  en:{
    "sc1-more":"Learn more →","sc7-more":"Learn more →",
    "nl-svc":"Services","nl-promo":"Offers","nl-vouch":"Gift vouchers","nl-contact":"Contact","nav-book":"Book now",
    "h-eyebrow":"Wellness centre · Prague 6 – Břevnov","h-title":"A place where <em>body<br>& mind</em> can rest",
    "h-sub":"Thai massages, cosmetics, permanent makeup and nail care — all under one roof with 17 years of expertise.",
    "h-cta1":"Book an appointment","h-cta2":"Our services","h-scroll":"Scroll",
    "s1":"years of experience","s2":"types of services","s3":"specialists","s4":"opening discount",
    "svc-ey":"Our services","svc-ttl":"Care that <em>truly works</em>",
    "svc-sub":"From relaxing massages to cosmetic treatments — our team of specialists handles every detail.",
    "sc1-n":"Massages","sc1-d":"Traditional Thai, oil, hot stone, herbal and aromatic massages. Release tension and restore balance.","sc1-p":"from 490 CZK",
    "sc2-n":"Couple massage","sc2-d":"Relaxation for two — a shared experience of calm and wellbeing. Perfect gift for couples and friends.","sc2-p":"from 1 490 CZK",
    "sc3-n":"Cosmetics","sc3-d":"Deep skin treatments, acne therapy, anti-aging procedures, waxing and makeup for any occasion.","sc3-p":"from 180 CZK",
    "sc4-n":"Permanent makeup","sc4-d":"Eyebrow microblading, PMU lips and brows. Natural results that last.","sc4-p":"from 3 500 CZK",
    "sc5-n":"Brows & lashes","sc5-d":"Lamination, lash extensions, lash lifting, tinting and shaping. Perfect eyes every day.","sc5-p":"from 150 CZK",
    "sc6-n":"Nails","sc6-d":"Manicure, pedicure, Shellac/Gellac, Footlogix and gel nails. Expert care for your hands and feet.","sc6-p":"from 250 CZK",
    "sc7-n":"Hairdressing","sc7-d":"Cuts, colouring, balayage and hair treatments for men, women and children. Professional care for your hair.","sc7-p":"from 100 CZK",
    "svc-book":"Book a service",
    "sf-ey":"About us","sf-ttl":"17 years of experience<br><em>caring for you</em>",
    "sf-sub":"GoldenZen was built with one vision — to offer Prague 6 a place where you truly feel good.",
    "sf-cta":"Book now",
    "pr-ey":"Current offers","pr-ttl":"Special <em>deals</em>","pr-sub":"Take advantage of our current promotions and treat yourself to more.",
    "pb1":"Opening","pt1":"30% discount","pd1":"Celebrate our opening with 30% off all services and products.","ph1":"All services included",
    "pb2":"Loyalty program","pt2":"10 visits + 1 free","pd2":"Come ten times and the eleventh visit is on us.","ph2":"Massages & cosmetics",
    "pb3":"Monthly offer","pt3":"30% off longer treatments","pd3":"This month get 30% off all treatments longer than 60 minutes.","ph3":"Treatments over 60 min",
    "vo-ey":"Gift vouchers","vo-ttl":"Give an <em>experience</em>,<br>not a thing",
    "vo-sub":"A GoldenZen gift voucher is the perfect present for any occasion — birthdays, anniversaries, or just because.",
    "vo-cta":"Order a voucher","vc-lbl":"GoldenZen · Gift Voucher","vc-val":"Wellness centre Prague 6",
    "vc-b1":"30% bonus","vc-b2":"on vouchers over 5 000 CZK","vc-b3":"40% bonus","vc-b4":"on vouchers over 15 000 CZK",
    "ct-ey":"Contact","ct-ttl":"Come <em>visit us</em>","ci-addr-l":"Address","ci-ph-l":"Phone","ci-hrs-l":"Opening hours",
    "ci-hrs-v":"Mon – Fri: 9am – 9pm<br>Sat – Sun: 10am – 9pm",
    "ci-ig-l":"Instagram","ci-fb-l":"Facebook",
    "bk-ey":"Online booking","bk-ttl":"Book your <em>time</em><br>today",
    "bk-sub":"Choose a service, pick a slot, and we'll take care of the rest. Fast, simple, online.",
    "bk-cta":"Go to booking","ft-copy":"© 2026 GoldenZen · Bělohorská 1686/118, Prague 6 – Břevnov","ft-legal":"Privacy Policy","ft-s1":"Hairdressing","ft-s2":"Men's hairdressing","ft-s3":"Women's hairdressing","ft-s4":"Hair colouring","ft-s5":"Massages","ft-s6":"Thai massages"
  }
}
